version: 1.0.{build}
branches:
    only : 
        - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-alpha"
before_build:
  - nuget restore
configuration: release
build:
  verbosity: minimal
test: off
build_success: 
    - ps: .\nuget\pack.ps1
artifacts:
  - path: Akka.Persistence.DocumentDb\bin\Release\Akka.Persistence.DocumentDb.dll
    name: Akka.Persistence.DocumentDb.dll
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: I0YFvLNC6gzBSeyYRHd9Nxt2yob+oRvUBsoXk+9z08aa/6ZLYwfeKcBF/0WADIEk
  skip_symbols: false
  artifact: /.*\.nupkg/